# Site settings
title: Foundry VTT Community
description: >
  A community effort to collect and organize information about Foundry Virtual Tabletop
lang: en-US

baseurl: "" # The subpath of the site, e.g. /blog/
url: "https://foundry-vtt-community.github.io/" # The base hostname & protocol for the site
git_address: https://github.com/foundry-vtt-community/wiki
git_edit_address: https://github.com/foundry-vtt-community/wiki/wiki

# Theme options from https://bootswatch.com/
# Comment out this to use default Bootstrap
bootwatch: superhero

# Build Settings
markdown: kramdown

plugins:
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-titles-from-headings
  - jekyll-optional-front-matter
  - jekyll-default-layout

# Files to exclude from build
exclude:
  - Gemfile
  - Gemfile.lock
  - .idea/
  - .gitignore
  - README.md
  - _docs/_Footer.md
  - _docs/_Sidebar.md
  - _docs/README.txt

# Default Settings
timezone: America/New_York
defaults:
# Doc Settings
- scope:
    path: _docs
    type: docs
  values:
    layout: docs
    sectionid: docs
    seo:
      type: "WebPage"

# Collection Settings
collections:
  docs:
    permalink: /wiki/:path/
    output: true
